version: '3'
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    ports:
       # The API for InfluxDB is served on port 8086
      - "8086:8086"
      - "8082:8082"
      # UDP Port
      - "8089:8089"
    volumes:
      # Mount for influxdb data directory
      - ./data/influxdb/data:/var/lib/influxdb
      # Mount for influxdb configuration
      - ./data/influxdb/config/:/etc/influxdb/
  mqtt:
      image: eclipse-mosquitto:latest
      container_name: mqtt
      restart: always
      ports:
        - "8883:1883"
        - "9001:9001"
      volumes:
        - ./data/mqtt/config:/mosquitto/config
        - ./data/mqtt/data:/mosquitto/data
        - ./data/mqtt/log:/mosquitto/log
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    restart: always
    links:
      # Telegraf necesita acceder a InfluxDB y a MQTT
      - influxdb
      - mqtt
    volumes:

      # Mount for telegraf configuration
      - ./data/telegraf/:/etc/telegraf/
      # Mount for Docker API access
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - influxdb
      - mqtt
    environment:
      HOSTNAME: "telegraf-getting-started"
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    links:
      - influxdb
    volumes:
      - ./data/grafana:/var/lib/grafana 
    environment:
      - GF_INSTALL_PLUGINS = grafana-clock-panel,briangann-gauge-panel,natel-plotly-panel,grafana-simple-json-datasource,natel-influx-admin-panel
  # chronograf nos permite administrar InfluxDB
  chronograf:
    image: chronograf:latest
    container_name: chronograf
    restart: always
    environment:
      RESOURCES_PATH: "/usr/share/chronograf/resources"
    volumes:
      # Base de datos de chronograf
      - ./data/chronograf/:/var/lib/chronograf/
    links:
      # Chronograf necesita acceder a InfluxDB
      - influxdb
    ports:
      # UI de chronograf en el puerto 8888
      - "8888:8888"