version: '3'
services:
  # InfluxDB (Base de datos de serie de tiempo)
  influxdb:
    image: arm32v7/influxdb:latest
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086"
    volumes:
      # Directorio de datos
      - ./data/influxdb/data:/var/lib/influxdb
      # Configuracion
      - ./data/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
  # Broker de MQTT
  mqtt:
      image: fstehle/rpi-mosquitto
      container_name: mqtt
      restart: always
      ports:
        - "1883:1883"
        - "8080:8080"
      volumes:
        - ./data/mqtt/config:/mosquitto/config
        - ./data/mqtt/data:/mosquitto/data
        - ./data/mqtt/log:/mosquitto/log
  # Telegraf se conecta a MQTT y grava los mensajes en InfluxDB
  telegraf:
    image: arm32v7/telegraf:1.5.2
    container_name: telegraf
    restart: always
    links:
      # Telegraf necesita acceder a InfluxDB y a MQTT
      - influxdb
      - mqtt
    volumes:
      # archivo de configuracion de telegraph (donde esta configurada la conexion a mqtt e influxdb)
      - ./data/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
      - mqtt
  grafana:
    image: fg2it/grafana-armhf:v4.6.3
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    links:
      - influxdb
    volumes:
      - ./data/grafana:/var/lib/grafana 
    environment:
      - GF_INSTALL_PLUGINS = grafana-clock-panel,briangann-gauge-panel,natel-plotly-panel,grafana-simple-json-datasource,natel-influx-admin-panel
  # chronograf nos permite administrar InfluxDB
  chronograf:
    image: arm32v7/chronograf:1.4.0.1
    container_name: chronograf
    restart: always
    volumes:
      # Base de datos de chronograf
      - ./data/chronograf/:/var/lib/chronograf/
    links:
      # Chronograf necesita acceder a InfluxDB
      - influxdb
    ports:
      # UI de chronograf en el puerto 8888
      - "8888:8888"