apiVersion: 1

datasources:
  - name: InfluxDB_v2_Flux
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    secureJsonData:
      token: my-super-secret-auth-token
    jsonData:
      version: Flux
      organization: nakama
      defaultBucket: telegraf
      tlsSkipVerify: true