apiVersion: 1
datasources:
  - name: InfluxDB_v1
    type: influxdb
    access: proxy
    database: telegraf
    user:
    url: http://influxdb:8086
    jsonData:
      httpMode: GET
    secureJsonData:
      password: